### ISSUE TITLE
Script will not recognize space in directory

### ISSUE THREAD

**Issue by olivejun** [wolfv6/rclone_jobber#4] opened 2018-08-02 15:09 UTC
I'm having a hard time having the job_backup_to_remote script to recognize a space in the path of my directory for my source. Here's the modified script:

rclone_jobber="/Users/Olive/Documents/GitHub/rclone_jobber" #path to rclone_jobber directory

source="/Volumes/Oliver/User Library"  <----- issue here
dest="pcloud:Production/Ableton"
move_old_files_to="dated_directory"
options="--stats=10s"
monitoring_URL=""

/Users/Olive/Documents/GitHub/rclone_jobber/rclone_jobber.sh "$source" "$dest" "$move_old_files_to" "$options" "$(basename $0)" "$monitoring_URL"

Here's the error message I get:

~ '/Users/Olive/Documents/GitHub/rclone_jobber/olive_backup/ableton_remote.sh'           07:58:52
ls: /Volumes/Oliver/User: No such file or directory
/Users/Olive/Documents/GitHub/rclone_jobber/rclone_jobber.sh: line 86: pidof: command not found
Back up in progress 2018-08-02_08:02:31 ableton_remote.sh

(I renamed job_backup_to_remote to ableton_remote)

Thanks!

**Comment by NoLooseEnds** [comment] 2018-08-02 15:13
Try to set the directory in ' '
`source="'/Volumes/Oliver/User Library'"`

Or you can also try:
`source="/Volumes/Oliver/User\ Library"`

**Comment by olivejun** [comment] 2018-08-02 15:16
I've tried both and it didn't work :(

It would output:

ls: /Volumes/Oliver/User: No such file or directory
ls: Library: No such file or directory

**Comment by wolfv6** [comment] 2018-08-02 16:44
@savi0000001, thank you for opening this issue.

What operating system are you on?
https://rclone.org/docs/ > If your names have spaces

What rclone command is your rclone_jobber.sh printing after the,
 "Back up in progress 2018-08-02_08:02:31 ableton_remote.sh"?

**Comment by wolfv6** [comment] 2018-08-05 18:09
@savi0000001,
The issue is fixed in rclone_jobber.sh v1.5.1
You will need to use extra quotes.
Instructions are in the tutorial at https://github.com/wolfv6/rclone_jobber/blob/master/rclone_jobber_tutorial.org#if-source-or-dest-path-contains-a-space

**Closed as completed** 2018-08-05 18:10 UTC
